# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_auto_20171011_1857'),
    ]

    operations = [
    ]
