# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0003_auto_20171011_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ['name']},
        ),
    ]
