# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0004_auto_20171020_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='refractive_index',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
